// In a real application, this would likely be a class or interface
// generated by an ORM like Prisma or TypeORM.

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  createdAt: Date;
}
