import React, { useState, useRef, useEffect } from 'react';
import { mockPolicies } from '../constants';
import type { Policy } from '@iniity/types';
import { generatePolicyFromPrompt } from '../services/geminiService';
import { MagicWandIcon } from '../components/icons/MagicWandIcon';
import { SparklesIcon } from '../components/icons/SparklesIcon';
import { InfoIcon } from '../components/icons/InfoIcon';

const PolicyCard: React.FC<{ policy: Policy, isNew: boolean }> = ({ policy, isNew }) => {
    const actionColor = policy.then.action === 'allow' ? 'text-emerald-400' : 'text-red-400';
    const cardRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (isNew) {
            cardRef.current?.classList.add('new-policy-highlight');
            const timer = setTimeout(() => {
                cardRef.current?.classList.remove('new-policy-highlight');
            }, 1500);
            return () => clearTimeout(timer);
        }
    }, [isNew]);


    return (
        <div ref={cardRef} className="bg-gray-900/50 rounded-lg shadow-lg border border-gray-800 p-4 font-mono text-sm transition-all">
            <div className="flex justify-between items-center mb-2">
                <h3 className="font-bold text-white text-base flex items-center gap-2">
                    {policy.name}
                    {policy.generatedBy === 'AI' && (
                        <div className="group relative flex items-center">
                            <SparklesIcon className="h-4 w-4 text-indigo-400" />
                             <span className="absolute left-1/2 -translate-x-1/2 bottom-full mb-2 w-max px-2 py-1 bg-gray-900 text-white text-xs rounded-md opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none border border-gray-700">
                                Generated by AI
                            </span>
                        </div>
                    )}
                </h3>
                <div className="flex items-center">
                    <span className={`mr-2 text-xs font-semibold ${policy.enabled ? 'text-gray-300' : 'text-gray-600'}`}>
                        {policy.enabled ? 'Enabled' : 'Disabled'}
                    </span>
                    <div className={`relative inline-block w-10 h-5 rounded-full transition-colors ${policy.enabled ? 'bg-indigo-600' : 'bg-gray-700'}`}>
                        <div className={`absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full shadow-md transform transition-transform ${policy.enabled ? 'translate-x-5' : ''}`}></div>
                    </div>
                </div>
            </div>

            {policy.rationale && (
                <div className="group relative flex items-start gap-2 text-xs text-gray-400 italic bg-gray-800/50 p-2 rounded-md mb-2 border border-gray-700">
                    <InfoIcon className="h-4 w-4 text-sky-400 flex-shrink-0 mt-0.5" />
                    <p>AI Rationale: "{policy.rationale}"</p>
                </div>
            )}

            <div className="bg-black/30 p-3 rounded-md">
                <div>
                    <span className="text-sky-400">IF</span>
                    <span className="text-gray-400"> (</span>
                </div>
                <div className="pl-4">
                    <p><span className="text-gray-500">source:</span> <span className="text-gray-300">{policy.if.sourceDID}</span></p>
                    <p><span className="text-gray-500">destination:</span> <span className="text-gray-300">{policy.if.destinationDID}</span></p>
                    <p><span className="text-gray-500">condition:</span> <span className="text-gray-300">"{policy.if.condition}"</span></p>
                </div>
                <div><span className="text-gray-400">)</span></div>
                <div className="mt-1">
                    <span className="text-sky-400">THEN</span>
                    <span className="text-gray-400"> -&gt; </span>
                    <span className={`${actionColor} font-bold`}>{policy.then.action.toUpperCase()}</span>
                    <span className="text-gray-300"> {policy.then.protocol}</span>
                </div>
            </div>
        </div>
    );
}

export const PolicyEditorView: React.FC = () => {
    const [policies, setPolicies] = useState<Policy[]>(mockPolicies.map(p => ({...p, generatedBy: 'user'})));
    const [prompt, setPrompt] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [newPolicyId, setNewPolicyId] = useState<string | null>(null);

    const handleGeneratePolicy = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!prompt.trim()) return;

        setIsLoading(true);
        setError(null);
        setNewPolicyId(null);
        try {
            const newPolicy = await generatePolicyFromPrompt(prompt);
            if (newPolicy) {
                setPolicies(prev => [newPolicy, ...prev]);
                setNewPolicyId(newPolicy.id);
                setPrompt('');
            } else {
                setError('Could not generate a valid policy from the prompt. Please try being more specific.');
            }
        } catch (err) {
            setError('An API error occurred. Please check your key and try again.');
            console.error(err);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="space-y-8">
            <section className="text-center">
                <h2 className="text-3xl md:text-4xl font-bold text-white mb-2">Policy Editor</h2>
                <p className="max-w-2xl mx-auto text-lg text-gray-400">
                    Define the rules of engagement for your network. Create fine-grained, identity-aware access policies using natural language.
                </p>
            </section>

            <section className="max-w-3xl mx-auto bg-gray-900/50 p-6 rounded-lg border border-gray-800">
                <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                    <MagicWandIcon />
                    Generate New Policy with AI Architect
                </h3>
                 <form onSubmit={handleGeneratePolicy} className="flex flex-col sm:flex-row items-center gap-3">
                    <input
                        type="text"
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="e.g., &quot;Deny my iPhone access to the Home Server&quot;"
                        className="w-full bg-gray-800/50 border border-gray-700 rounded-lg p-3 text-gray-300 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                        disabled={isLoading}
                    />
                    <button type="submit" disabled={isLoading || !prompt.trim()} className="w-full sm:w-auto flex items-center justify-center gap-2 px-5 py-3 bg-indigo-600 rounded-lg text-white font-semibold hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all">
                        {isLoading ? (
                            <div className="animate-spin rounded-full h-5 w-5 border-t-2 border-b-2 border-white"></div>
                        ) : (
                           <SparklesIcon className="h-5 w-5" />
                        )}
                        Generate
                    </button>
                </form>
                {error && <p className="text-red-400 text-sm mt-3">{error}</p>}
            </section>

            <section className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {policies.map(policy => (
                    <PolicyCard key={policy.id} policy={policy} isNew={policy.id === newPolicyId} />
                ))}
            </section>
        </div>
    );
};